CREATE DATABASE IF NOT EXISTS `onlinefoodphp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `onlinefoodphp`;

CREATE TABLE `admin` (
  `adm_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(222) NOT NULL,
  `password` VARCHAR(222) NOT NULL,
  `email` VARCHAR(222) NOT NULL,
  `code` VARCHAR(222) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`adm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dishes` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `rs_id` INT NOT NULL,
  `title` VARCHAR(222) NOT NULL,
  `slogan` VARCHAR(222) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `img` VARCHAR(222) NOT NULL,
  PRIMARY KEY (`d_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `remark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `frm_id` INT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `remark` MEDIUMTEXT NOT NULL,
  `remarkDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `restaurant` (
  `rs_id` INT NOT NULL AUTO_INCREMENT,
  `c_id` INT NOT NULL,
  `title` VARCHAR(222) NOT NULL,
  `email` VARCHAR(222) NOT NULL,
  `phone` VARCHAR(222) NOT NULL,
  `url` VARCHAR(222) NOT NULL,
  `o_hr` VARCHAR(222) NOT NULL,
  `c_hr` VARCHAR(222) NOT NULL,
  `o_days` VARCHAR(222) NOT NULL,
  `address` TEXT NOT NULL,
  `image` TEXT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`rs_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `res_category` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(222) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`c_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(222) NOT NULL,
  `f_name` VARCHAR(222) NOT NULL,
  `l_name` VARCHAR(222) NOT NULL,
  `email` VARCHAR(222) NOT NULL,
  `phone` VARCHAR(222) NOT NULL,
  `password` VARCHAR(222) NOT NULL,
  `address` TEXT NOT NULL,
  `status` INT NOT NULL DEFAULT '1',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`u_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users_orders` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `title` VARCHAR(222) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(222),
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`o_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
